---
- name: "{{ 'Prune' if inception_prune else 'Deploy' }} Inception images"
  community.docker.docker_image:
    name: "{{ image_item.image.name }}"
    state: "{{ 'absent' if inception_prune else 'present' }}"
    source: "{{ 'build' if image_item.image.build_folder is defined else 'pull' }}"
    build: "{{ {'path': inception_src_path + '/inception/requirements/' + image_item.image.build_folder, 'pull': true} if image_item.image.build_folder is defined else omit }}"
    pull:
      platform: "linux/{{ deb_architecture[ansible_architecture] | default(ansible_architecture) }}"
  loop: "{{ inception_containers }}"
  loop_control:
    loop_var: image_item
  when: image_item.image.name is defined