services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:${WORDPRESS_PATH}
    networks:
      - network
    restart: on-failure
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_ABSOLUTE_URI: https://${DOMAIN_NAME}/phpmyadmin/
    depends_on:
      - mariadb
    networks:
      - network
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:${WORDPRESS_PATH}
    networks:
      - network
    restart: on-failure
  
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
